### PR TITLE
Spark 3.0.1 upgrade

### LINKED ISSUE #33: Support Spark 3.0.0
@jahstreet Just to put this under your radar as Spark 3.0.0 has just been released, with I guess better support for K8s.

https://spark.apache.org/news/spark-3-0-0-released.html

### LINKED ISSUE #34: Liveness & rediness checks timeout on Livy
Currently liveness is being checked on `/batches` endpoint:
https://github.com/jahstreet/spark-on-kubernetes-helm/blob/a1fd2ac19580feb0d9469c1d7cadd8630710ac13/charts/livy/templates/statefulset.yaml#L33

When there is a bigger number of batches, these check timeout occasionally:
```
Events:
  Type     Reason     Age                 From                                                    Message
  ----     ------     ----                ----                                                    -------
  Warning  Unhealthy  54m (x56 over 10d)  kubelet, ip-XX  Readiness probe failed: Get http://XX:8998/batches: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  54m (x59 over 10d)  kubelet, ip-XX  Liveness probe failed: Get http://XX:8998/batches: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Would it be ok to add `?size=1` to limit response size, or at least to have an option to disable these checks on livy chart?

### LINKED ISSUE #38: jupyter-sparkmagic chart uses k8s APIs Removed In 1.16
Cannot install jupyter-sparkmagic 1.0.0 chart on k8s 1.16+
Error occurred: **no matches for kind "Deployment" in version "apps/v1beta2"**

https://github.com/jahstreet/spark-on-kubernetes-helm/blob/96f2521b0e20f30fe2dcede5c81239698bd01fb0/charts/jupyter-sparkmagic/templates/deployment.yaml#L2

Deprecated APIs Removed In 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

### PR DESCRIPTION
**Pull request by jahstreet**

### CODE REVIEW

**Comment by jahstreet** [comment]
Left to update `spark-monitoring` and `jupyter-sparkmagic` charts, Jupyter image version, docs.

**Review by cekicbaris — APPROVED** [review]

**Comment by jahstreet** [comment]
Will upgrade directly to 3.0.1 to support K8s API 1.18.0.

**Comment by cekicbaris** [comment]
Will look forward to test it in our environment. @jahstreet any idea when it will be available?

**Comment by jahstreet** [comment]
Currently testing locally. Tomorrow will cut the release and deploy all the artifacts.

**Pull request merged**
